// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// soft_thresh
double soft_thresh(double z, double lambda);
RcppExport SEXP _staRz_soft_thresh(SEXP zSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(soft_thresh(z, lambda));
    return rcpp_result_gen;
END_RCPP
}
// LQA_lasso
arma::vec LQA_lasso(arma::mat X, arma::vec Y, arma::vec beta_start, double lambda, double tol, int max_it);
RcppExport SEXP _staRz_LQA_lasso(SEXP XSEXP, SEXP YSEXP, SEXP beta_startSEXP, SEXP lambdaSEXP, SEXP tolSEXP, SEXP max_itSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta_start(beta_startSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_it(max_itSEXP);
    rcpp_result_gen = Rcpp::wrap(LQA_lasso(X, Y, beta_start, lambda, tol, max_it));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_staRz_soft_thresh", (DL_FUNC) &_staRz_soft_thresh, 2},
    {"_staRz_LQA_lasso", (DL_FUNC) &_staRz_LQA_lasso, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_staRz(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
